#!/bin/bash

cat <<"EOF"
   _____                      __  __
  / ____|                    |  \/  |
 | |  __  __ _ _______ _ __  | \  / | ___ _ __  _   _
 | | |_ |/ _` |_  / _ \ '__| | |\/| |/ _ \ '_ \| | | |
 | |__| | (_| |/ /  __/ |    | |  | |  __/ | | | |_| |
  \_____|\__,_/___\___|_|    |_|  |_|\___|_| |_|\__,_|

EOF

if [ -f ".gazer.bid" ]; then
  build_id=$(cat .gazer.bid)
  echo "                                      > $build_id <"
fi

sleep 0.5

if [ ! -f "run.gazer" ]; then
  echo "The file '.gather.run' does not exist!"
  exit 1
fi

started=false

echo "Choose an action:"
if [ -f ".gazer.pid" ]; then
  started=true

  echo "1) Restart"
  echo "2) Stop"
  echo "3) Watch Log"

  if [ ! -f ".gazer.log" ]; then
    touch ".gazer.log"
  fi
else
  echo "1) Start"
fi

cmd=""

while true; do
  read -rp "Enter command number (1, 2, etc): " input
  if [[ -z "$input" ]]; then
    exit 0
  elif [[ "$started" = true && "$input" =~ ^[1-3]$ ]]; then
    cmd="$input"
    break
  elif [[ "$started" = false && "$input" = "1" ]]; then
    cmd="$input"
    break
  else
    echo "Please enter a valid number."
  fi
done

if [ "$cmd" == "3" ]; then
  watch -n 0.1 cat .gazer.log
  echo "Success"
  exit 0
fi

if [ -f ".gazer.pid" ]; then
  OLD_PID=$(cat .gazer.pid)
  if ps -p "$OLD_PID" >/dev/null 2>&1; then
    if [ "$cmd" == "2" ]; then
      pkill -P "$OLD_PID"
      rm .gazer.pid .gazer.log .gazer.bid || true
      echo "Success"
      exit 0
    else
      pkill -P "$OLD_PID"
    fi
  fi
fi

if [ "$cmd" == "2" ]; then
  rm .gazer.pid .gazer.log .gazer.bid || true
  echo "Success"
  exit 1
fi

chmod +x run.gazer

nohup ./run.gazer >.gazer.log 2>&1 &
NEW_PID=$!
echo $NEW_PID >.gazer.pid

echo "Success"

head /dev/urandom | tr -dc A-Z0-9 | head -c 5 | sed 's/./& /g' >.gazer.bid
