#!/bin/bash

if [ "$1" == "log" ]; then
  if ! command -v watch &>/dev/null; then
    echo "Error: The 'watch' command was not found. Please install it and try again."
    exit 1
  fi
  watch -n 0.1 .gazer.log
  exit 0
fi

if [ ! -f ".gazer.run" ]; then
  echo "Error: The '.gazer.run' file was not found."
  exit 1
fi

if [ -f ".gazer.pid" ]; then
  OLD_PID=$(cat .gazer.pid)
  if ps -p "$OLD_PID" >/dev/null 2>&1; then
    if [ "$1" == "stop" ]; then
      echo "Terminating process with PID: $OLD_PID"
      kill "$OLD_PID"
      echo "Process with PID $OLD_PID has been terminated."
      rm .gazer.pid
      exit 0
    else
      echo "Terminating old process with PID: $OLD_PID"
      kill "$OLD_PID"
    fi
  else
    echo "Process with PID $OLD_PID no longer exists."
  fi
fi

if [ "$1" == "stop" ]; then
  echo "The process is not running, as the .gazer.pid file was not found."
  exit 1
fi

chmod +x .gazer.run

echo "Starting a new process..."
./.gazer.run >.gazer.log 2>&1 &
NEW_PID=$!
echo $NEW_PID >.gazer.pid

echo "Process started with PID: $NEW_PID"
echo "All logs will be recorded in the .gazer.log file."
echo "Try 'gaze stop' to stop program."
echo "Try 'gaze log' to see logs in real time."
